language: python
sudo: false
python: 2.7
cache: pip
env:
  - TOXENV="py27_django18"
  - TOXENV="py27_django19"
  - TOXENV="py27_django10"
  - TOXENV="py27_django11"
install:
  - pip install --upgrade pip setuptools --quiet
  - pip install -r requirements.txt --trusted-host dist.pinaxproject.com --quiet
  - pip install Image --quiet
  - pip install tox --quiet
  - echo -e "LOCAL_INSTALLED_APPS = ['multicurrency',]\n" > local_settings.py
  - echo -e "MULTICURRENCY = {'client_id':'','client_secret':'','access_key':'','access_secret':'',}" >> local_settings.py
script:
  - tox -e $TOXENV
